<?php
define('ERROR_REPORTING',1);
define('DEFAULT_ERROR_LOG',0);
define('DB_LOG',0);
define('ROOT_DIR','/var/www/html/subhendu_todo_list_com/');
define('LIB_DIR',ROOT_DIR.'libs/');
define('UTILITY_DIR',ROOT_DIR.'utility/');
define('DB_MIGRATION',ROOT_DIR.'db_migration/');
?>